name: Build Guix Installer

on:
  push:
    branches:
      - main

  schedule:
    # build every week
    - cron: "0 0 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Guix
        uses: ymfsing/guix-install-action@v1

      # - name: Add nonguix key
      #   run: |
      #     sudo guix archive --authorize < './guix/key.pub'

      - name: Build ISO
        run: |

          # Write out the channels file so it can be included
          guix time-machine -C './guix/base-channels.scm' -- describe -f channels > './guix/channels.scm'

          # Build the image
          image=$(guix time-machine -C './guix/channels.scm' -- system image -t iso9660 --substitute-urls='https://substitutes.nonguix.org https://bordeaux.guix.gnu.org https://ci.guix.gnu.org' './guix/installer.scm')

          # Copy the image to the local folder with a better name
          export RELEASE_TAG=$(date +"%Y%m%d%H%M")
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          cp $image ./guix-installer-$RELEASE_TAG.iso
          sha256sum ./guix-installer-$RELEASE_TAG.iso > ./guix-installer-$RELEASE_TAG.iso.sha256sum
          echo "SHA256_ISO=$(cat ./guix-installer-$RELEASE_TAG.iso.sha256sum)" >> $GITHUB_ENV

      - name: Prepare Release Notes
        run: |
          echo $'This installer image was prepared with the following channel configuration:\r\n\r\n```\r\n' > release-notes.md
          cat ./guix/channels.scm >> release-notes.md
          echo $'\r\n```' >> release-notes.md
          echo $'SHA256 Checksums:\r\n\r\n```\r\n' >> release-notes.md
          cat ./guix-installer-$RELEASE_TAG.iso.sha256sum >> release-notes.md
          echo $'\r\n```' >> release-notes.md          

      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          name: Guix Installer - ${{ env.RELEASE_TAG }}
          tag_name: v${{ env.RELEASE_TAG }}
          body_path: release-notes.md
          files: guix-installer-${{ env.RELEASE_TAG }}.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ymfsing/guix-installer

      - name: Remove old release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 7
          delete_tags: true
          # delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
